language: csharp
mono: 3.12.0

env: TARGET_LANG=dotnet

matrix:
  include:
    - env: TARGET_LANG=java

    - env: TARGET_LANG=ruby USE_RVM=ruby-2.0.0
    - env: TARGET_LANG=ruby USE_RVM=ruby-2.1.2
    - env: TARGET_LANG=ruby USE_RVM=ruby-2.2.0
    - env: TARGET_LANG=ruby USE_RVM=jruby-1.7

    - env: TARGET_LANG=javascript
    
    - env: TARGET_LANG=go

before_install:
  - export EnableNuGetPackageRestore=true
  # https://github.com/travis-ci/travis-ci/issues/2839
  - export JAVA_HOME="$(dirname $(dirname $(readlink -e $(which javac))))"
  # install jq if its not already there
  - which jq || sudo apt-get install -y jq

script:
  - '[ -z "$USE_RVM" ] || (rvm use $USE_RVM || (rvm install $USE_RVM && rvm use $USE_RVM))'
  - "cd $TARGET_LANG; make"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
