language: csharp
mono: 3.12.0

env:
  - TARGET_LANG=dotnet
  - TARGET_LANG=java
  - TARGET_LANG=ruby USE_RVM=ruby-2.0
  - TARGET_LANG=ruby USE_RVM=ruby-2.1
  - TARGET_LANG=ruby USE_RVM=ruby-2.2
  - TARGET_LANG=ruby USE_RVM=jruby
  - TARGET_LANG=javascript
  - TARGET_LANG=go

before_install:
  - export EnableNuGetPackageRestore=true
  # https://github.com/travis-ci/travis-ci/issues/2839
  - export JAVA_HOME="$(dirname $(dirname $(readlink -e $(which javac))))"
  # install jq if its not already there
  - which jq || sudo apt-get install -y jq
  # configure RVM if needed
  - '[ -z "$USE_RVM" ] || (rvm use --default $USE_RVM || (rvm install $USE_RVM && rvm use --default $USE_RVM))'

script:
  - "cd $TARGET_LANG && make"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
