# https://github.com/travis-ci/travis-ci/issues/649
# Hack to install mono
language: c

rvm:
  - 2.0.0
  - jruby

before_install:
 - wget "http://download.mono-project.com/archive/3.2.7/macos-10-x86/MonoFramework-MDK-3.2.7.macos10.xamarin.x86.dmg"
 - hdid "MonoFramework-MDK-3.2.7.macos10.xamarin.x86.dmg"
 - sudo installer -pkg "/Volumes/Mono Framework MDK 3.2.7/MonoFramework-MDK-3.2.7.macos10.xamarin.x86.pkg" -target /

script: "make"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
