language: csharp
mono: latest
sudo: false

before_install:
  - export EnableNuGetPackageRestore=true

script: "mono .nuget/NuGet.exe restore Gherkin.CSharp.sln;xbuild /p:Configuration=Debug;.nuget/NuGet.exe pack dotnet/Gherkin.NuGetPackages/Gherkin.nuspec"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
